### Basical auguments
# --- Directory where your model performance will be saved.
model_path: your/path/to/RCIPred/ 
folder_name: Model/
# --- Selection use model (default: Base) and use dataset (default: DatasetA)
model_name: Base
use_dataset: DataSetA
use_testset: # None
# --- How to split dataset
split_type: random
test_size: 0.1
test_column: # None
test_order: # None

### Model Parameters
# --- Hyper parameters (for cross-validation)
params_dict: 
  dropout_rate: 
    - 0.4
    - 0.5
  l1_alpha: 
    - 0.0001
  kernel_size: 
    - 9
  num_kernel: 
    - 8
# Hyper parameters (for train and test)
dropout_rate: 0.4
l1_alpha: 0.0001
kernel_size: 9
num_kernel: 8
# --- Input data size
rna_input_size: 4
ecfp_input_size: 2048
# --- Design of learning
batch_size: 64
num_epoch: 100              # (for train)
num_epoch_cv: 100           # (for cross-validation)
cv_fold: 5                  # (for cross-validation)
trained_weight_path: # None # (for test & permutation importance)

### Mode 
# --- Creating folders for result saving
init: True
# --- Cross validation
cv: False
# --- Train
train: False
# --- Test
test: False
# --- Permutation importance
pi: False
